// <auto-generated />
namespace MastersRacers.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewsItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewsItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201711092043366_NewsItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
